# Generated by Django 3.2.7 on 2021-09-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProduct',
            new_name='CardProduct',
        ),
    ]
