# Generated by Django 3.2.7 on 2021-09-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20210909_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='products',
            field=models.ManyToManyField(blank=True, to='delivery.CardProduct'),
        ),
    ]
