# Generated by Django 3.2.7 on 2021-09-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_meal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmeal',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
