# Generated by Django 3.2.7 on 2021-09-10 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0004_alter_card_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('in_orders', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_meals',
                                           to='delivery.cart', verbose_name='Cart')),
            ],
            options={
                'verbose_name': 'Cart product',
                'verbose_name_plural': 'Cart products',
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='card',
            name='products',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customers_order',
            new_name='orders',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_user',
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='meal',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garus',
                                    to='delivery.customer'),
        ),
        migrations.DeleteModel(
            name='CardProduct',
        ),
        migrations.AddField(
            model_name='cartmeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.meal',
                                    verbose_name='Meal'),
        ),
        migrations.AddField(
            model_name='cartmeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.customer',
                                    verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='cart_meals', to='delivery.CartMeal'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.cart'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
