# Generated by Django 3.2.7 on 2021-09-11 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0006_auto_20210911_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmeal',
            options={'verbose_name': 'Cart meal', 'verbose_name_plural': 'Cart meals'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='meals',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_meals', to='delivery.CartMeal'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
