# Generated by Django 3.2.7 on 2021-09-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20210911_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='meals',
            field=models.ManyToManyField(blank=True, null=True, related_name='meals_set', to='delivery.CartMeal'),
        ),
    ]
