# Generated by Django 3.2.7 on 2021-09-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20210913_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurant'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
