# Generated by Django 3.2.7 on 2021-09-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_auto_20210914_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurateur',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurateur'),
        ),
    ]
