# Generated by Django 3.2.7 on 2021-09-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='CourierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.order')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.courier')),
            ],
        ),
    ]
