# Generated by Django 3.2.7 on 2021-09-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_auto_20210918_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourierOrder',
        ),
    ]
