# Generated by Django 3.2.7 on 2021-09-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_delete_courierorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.courier'),
        ),
    ]
