# Generated by Django 3.2.7 on 2021-09-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_order_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.courier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Waiting for'), ('accepted for cooking', 'Accepted for cooking'), ('cooked', 'Cooked'), ('handed over to the courier', 'Handed over to the courier'), ('delivered', 'Delivered')], default='new', max_length=100),
        ),
    ]
