# Generated by Django 3.2.7 on 2021-09-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_auto_20210918_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Waiting for'), ('accepted for cooking', 'Accepted for cooking'), ('cooked', 'Cooked'), ('handed over to the courier', 'Accepted by the courier'), ('delivered', 'Delivered')], default='new', max_length=100),
        ),
    ]
