# Generated by Django 3.2.7 on 2021-09-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_complaint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant_address',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
