# Generated by Django 3.2.7 on 2021-09-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_order_restaurant_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_meal',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_meal',
            field=models.ManyToManyField(blank=True, null=True, to='delivery.CartMeal'),
        ),
    ]
